server:
  port: 8081
spring:
  application:
    name: service-provider
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka/ # one eureka server
      # defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/ # two eureka server
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/, http://localhost:8763/eureka/ # three eureka server