server:
  port: 8082
spring:
  application:
    name: eureka-client-2
eureka:
  instance:
    metadata-map:
      zone: zone2
  client:
    register-with-eureka: true
    region: china-east #设置region
    availability-zones:
      china-east: zone1, zone2 #设置region下可对应的Zone
    serviceUrl:
      zone1: http://localhost:8761/eureka/, http://localhost:8762/eureka/
      zone2: http://localhost:8763/eureka/, http://localhost:8764/eureka/