server:
  port: 8081
spring:  application:    name: eureka-client-1
  cloud:
    discovery:
      enabled: true
eureka:  client:    service-url:#      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka