eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

---
spring:
  profiles: eureka1
  application:
    name: eureka-server1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost

---
spring:
  profiles: eureka2
  application:
    name: eureka-server2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost