---
server:  port: 8761
spring:
  application:    name: eureka-server-1  profiles: zone1-a
eureka:
  instance:
    metadata-map:
      zone: zone1
  client:    region: china-east    service-url:      zone1: http://localhost:8761/eureka,http://localhost:8762/eureka
      zone2: http://localhost:8763/eureka,http://localhost:8764/eureka
    availability-zones:      china-east: zone1,zone2
      
---
server:
  port: 8762
spring:
  application:
    name: eureka-server-2
  profiles: zone1-b
eureka:
  instance:
    metadata-map:
      zone: zone1
  client:
    region: china-east
    service-url:
      zone1: http://localhost:8761/eureka,http://localhost:8762/eureka
      zone2: http://localhost:8763/eureka,http://localhost:8764/eureka
    availability-zones:
      china-east: zone1,zone2
      
---
server:
  port: 8763
spring:
  application:
    name: eureka-server-3
  profiles: zone2-a
eureka:
  instance:
    metadata-map:
      zone: zone2
  client:
    region: china-east
    service-url:
      zone1: http://localhost:8761/eureka,http://localhost:8762/eureka
      zone2: http://localhost:8763/eureka,http://localhost:8764/eureka
    availability-zones:
      china-east: zone1,zone2
      
---
server:
  port: 8764
spring:
  application:
    name: eureka-server-4
  profiles: zone2-b
eureka:
  instance:
    metadata-map:
      zone: zone2
  client:
    region: china-east
    service-url:
      zone1: http://localhost:8761/eureka,http://localhost:8762/eureka
      zone2: http://localhost:8763/eureka,http://localhost:8764/eureka
    availability-zones:
      china-east: zone1,zone2