eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 0
    
---
spring:
  profiles: eureka1
  application:
    name: eureka-server-1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka, http://${eureka.instance.hostname}:8763/eureka

---
spring:
  profiles: eureka2
  application:
    name: eureka-server-2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka, http://${eureka.instance.hostname}:8763/eureka
      
---
spring:
  profiles: eureka3
  application:
    name: eureka-server-3
server:
  port: 8763
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka, http://${eureka.instance.hostname}:8762/eureka
      
      
