---
server:
  port: 8081
spring:
  application:
    name: eureka-client-1
  profiles:
    - zone1
eureka:
  instance:
    metadata-map:
      zone: zone1
  client:
    register-with-eureka: true
    fetch-registry: true
    region: china-east
    service-url:
      zone1: http://localhost:8761/eureka,http://localhost:8762/eureka
      zone2: http://localhost:8763/eureka,http://localhost:8764/eureka

---
server:
  port: 8082
spring:
  application:
    name: eureka-client-2
  profiles:
    - zone2
eureka:
  instance:
    metadata-map:
      zone: zone2
  client:
    register-with-eureka: true
    fetch-registry: true
    region: china-east
    service-url:
      zone1: http://localhost:8761/eureka,http://localhost:8762/eureka
      zone2: http://localhost:8763/eureka,http://localhost:8764/eureka