server:
  port: 8763
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka # three eureka server
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
