server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:8761/eureka # one eureka server
      # defaultZone: http://localhost:8762/eureka # two eureka server
      defaultZone: http://localhost:8762/eureka, http://localhost:8763/eureka # three eureka server
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
