package com.as1124.ch14test.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.as1124.ch14test.db.City;
import com.as1124.ch14test.db.Country;
import com.as1124.ch14test.db.Province;

import com.as1124.ch14test.db.CityDao;
import com.as1124.ch14test.db.CountryDao;
import com.as1124.ch14test.db.ProvinceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig countryDaoConfig;
    private final DaoConfig provinceDaoConfig;

    private final CityDao cityDao;
    private final CountryDao countryDao;
    private final ProvinceDao provinceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        countryDaoConfig = daoConfigMap.get(CountryDao.class).clone();
        countryDaoConfig.initIdentityScope(type);

        provinceDaoConfig = daoConfigMap.get(ProvinceDao.class).clone();
        provinceDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        countryDao = new CountryDao(countryDaoConfig, this);
        provinceDao = new ProvinceDao(provinceDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(Country.class, countryDao);
        registerDao(Province.class, provinceDao);
    }
    
    public void clear() {
        cityDaoConfig.clearIdentityScope();
        countryDaoConfig.clearIdentityScope();
        provinceDaoConfig.clearIdentityScope();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public CountryDao getCountryDao() {
        return countryDao;
    }

    public ProvinceDao getProvinceDao() {
        return provinceDao;
    }

}
